### ISSUE TITLE
Make a custom phrase like changing "playing" to "write" / "coding" 

### ISSUE THREAD

**Issue by artur309** [VisualDevelopment/DiscordRPC-for-Visual-Studio#10]
Since it's song gaming, i prefer say other thing then "playing"
So if was possible change that, or even better, make a custom text, ex:
"Coding Visual Studio"

This feature would be a goof feature to be honest

**Comment by ben-1975** [comment]
I like this idea, "Using Visual Studio" or "Coding with Visual Studio" would be much nicer.  But if that can't be done, how about just adding the word 'with' so it says "Playing with Visual Studio"?

**Comment by Issung** [comment]
I would also like this feature, currently, though you cannot change that text in discord, I made this feature request on discord's feedback site, you can view it and upvote it here: https://support.discord.com/hc/en-us/community/posts/360069797672-Rich-Presence-Playing-A-Game-custom-title-

**Comment by VisualDevelopment** [comment]
Oh, I just realized, as Issung said, this isn't possible, I apologize.
