### ISSUE TITLE
C files not supported part 2

### ISSUE THREAD

**Issue by lauralex** [VisualDevelopment/DiscordRPC-for-Visual-Studio#16]
**Bug description:**

I don't know why you close issues for no reason. C files are not supported. The source code is almost correct, but it seems that you should use another value for the key ".C". I used "c file" and "C file" and it works, but it doesn't display anything because it's not a valid image file name of course. So, maybe you should reupload the image for the C file.

EDIT:

Workaround: edit the "Constants.cs" source file and modify the value for the key ".C" to: "cpp" and "C file". This way it shows a c++ image but the tooltip text would be "C file"

**Comment by VisualDevelopment** [comment]
The code here is more up to date than the extension in the marketplace
![code](https://me.has-no-bra.in/KvUqyS.png)
In the code of the repository here it shows that it _should_ work, It would be helpful if you could attach some images if what's happening exactly
I was tired and my mind thought it was a good idea to close the issues without asking for more info
If it's actually not working then Discord did a backend change and it doesn't accept one letter image names even though I had a valid image, as seen here:
![image](https://me.has-no-bra.in/8O0Lbc.png)
Apologies for the inconvenience

**Comment by VisualDevelopment** [comment]
Hey, I'm investigating into the issue, and it seems like Discord's developer portal allows 1 char names, but it sends me the following error:
```json
{
    "cmd": "SET_ACTIVITY",
    "data": {
        "code": 4000,
        "message": "child \"activity\" fails because [child \"assets\" fails because [child \"large_text\" fails because [\"large_text\" length must be at least 2 characters long]]]"
    },
    "evt": "ERROR",
    "nonce": "5"
}
```

**Comment by VisualDevelopment** [comment]
Fixed on latest commit!
