### ISSUE TITLE
[Help] How to toggle the extension options

### ISSUE THREAD

**Issue by Megas97** [VisualDevelopment/DiscordRPC-for-Visual-Studio#17]
Hello,

Sorry if my question is really stupid but I couldn't figure out how to change the settings of the extension once it's installed. I want to disable the time reset when I switch files but have no idea where to access these settings in Visual Studio 2019. If I go to Manage Extensions from the top menu bar there are only options to Disable or Uninstall extensions but there is no options/settings button.

Greetings,
Simeon

**Comment by VisualDevelopment** [comment]
Sorry, saw your question and forgot to answer! :O
You open the "Tools" menu from the top menu bar then hover over "Discord Rich Presence" then click the only thing in the submenu, "Settings..."

**Comment by Megas97** [comment]
Thank you! :)
