### ISSUE TITLE
C Support & Manual discord update

### ISSUE THREAD

**Issue by Tydox** [VisualDevelopment/DiscordRPC-for-Visual-Studio#5]
support for c file type, also when you update the settings then you have to restart vs to take effect

**Comment by VisualDevelopment** [comment]
I can't tell if the second part is a suggestion or an issue, if it's a bug, please don't suggest a feature and report a bug at the same time. Also, please use the templates when making issues.

**Comment by VisualDevelopment** [comment]
Issue is stale, closing.
