### ISSUE TITLE
Extension settings are reset on every VS update

### ISSUE THREAD

**Issue by 13xforever** [VisualDevelopment/DiscordRPC-for-Visual-Studio#7]
**Describe the bug**
When VS applies a new update, DiscrodRPC settings are reset to defaults.

**To Reproduce**
1. Change settings
2. Install VS update
3. Randomly notice that your Secret Mode is disabled again

**Expected behavior**
Settings are preserved between updates, like for every other extension

**Desktop (please complete the following information):**
 - OS: Windows 10 2004, but it doesn't really matter
 - Browser: ???
 - Extension Version: 5.3

**Additional context**
I've yet to test if changing the components through vs installer affects the extension in the same way.

**Comment by kieranirving** [comment]
Have noticed the same issue happening to me as well.

**Comment by VisualDevelopment** [comment]
I think I'm not handling settings correctly, reading the docs and it should be fixed soon!

**Comment by lauralex** [comment]
I think you should use the Upgrade() method. In my case the configuration file is saved here: C:\Users\R0ot\AppData\Local\Microsoft_Corporation\DefaultDomain_Url_wt0kycywduqvhjwi4kalu5tmjzu3gqy0\16.6.30225.117\user.config and here: C:\Users\R0ot\AppData\Local\Microsoft_Corporation\DefaultDomain_Url_wt0kycywduqvhjwi4kalu5tmjzu3gqy0\16.6.30309.148\user.config

**Comment by VisualDevelopment** [comment]
Oh, I missed that while reading about settings. Great!

**Comment by VisualDevelopment** [comment]
Implemented the fix!
