### ISSUE TITLE
F# unrecognizable extension

### ISSUE THREAD

**Issue by Krakenus00** [VisualDevelopment/DiscordRPC-for-Visual-Studio#8]
**Overview**
Discord is showing the icon for an unrecognizable document when editing F# files.

**Steps to reproduce the behavior**
1. Open any F# file.
2. Start editing.
3. Check your profile status in discord.

**Expected behavior**
Discord is showing the F# icon when editing *.fs, *.fsx, *.fsi, *.fsscript files.

**Screenshots**
![Discord status](https://i.imgur.com/VBsoUMq.png)

**Desktop**
 - OS: Windows 10 x64 v.1909 build 18363.778
 - Discord: Stable 60561 (0224963)
 - Visual Studio: Community 2019 v.16.6.0

**Comment by VisualDevelopment** [comment]
Added, await the new release.
