### ISSUE TITLE
Add support for recognizing i'm coding in C

### ISSUE THREAD

**Issue by ne0rrmatrix** [VisualDevelopment/DiscordRPC-for-Visual-Studio#9]
Installed extension. It works perfectly if i code in C++ or C# etc but when i am writing a console app in C not C++ it displays nothing. If you could add support for C language in Visual Studio 2019 it would be a nice feature to have.

I should mention if i open a .c file or a project with just .c file open it will not be recognized by discord and show nothing under my name in discord.

**Comment by VisualDevelopment** [comment]
This doesn't look right, in the source code it already supports the .c extension. Could you please attach the action log from the extension?
